version: "3"
services:
    web:
        build: docker
        container_name: '${APP_NAME}'
        ports:
            - 8081:80
        volumes:
            - .:/var/www/html
        extra_hosts:
            - host.docker.internal:host-gateway
    db:
        image: mysql:5.7
        restart: always
        environment:
            MYSQL_DATABASE: '${APP_MYSQL_DATABASE}'
            MYSQL_USER: '${DB_USERNAME}'
            MYSQL_PASSWORD: '${DB_PASSWORD}'
            MYSQL_ROOT_PASSWORD: 'root'
        command:
            - --character-set-server=utf8mb4
            - --collation-server=utf8mb4_unicode_ci
            - --default-authentication-plugin=mysql_native_password
        ports:
            - '33067:3306'
        expose:
            - '33067'
        volumes:
            - ./docker/mysql/data:/var/lib/mysql
            - db_data:/var/lib/mysql
volumes:
    db_data:
