#name: remote ssh command
#on:
#  push:
#    branches:
#      - main
#jobs:
#  deploy:
#    name: Deploy
#    runs-on: ubuntu-22.04
#
#    permissions:
#      id-token: write
#      contents: read
#
#    steps:
#      - uses: actions/checkout@v2
#
#      - name: Configure AWS Credentials
#        uses: aws-actions/configure-aws-credentials@v1
#        with:
#          role-to-assume: arn:aws:iam::932592296700:role/githubAwsRoleActions
#          aws-region: eu-west-1
#
#      - name: download project
#        working-directory: /var/www/html/economyControl
#        run: |
#          git pull


on:
  push:
    branches: [ main ]

jobs:
  Deploy:
    runs-on: ubuntu-latest

    steps:
      - name: executing remote ssh commands using password
          uses: appleboy/ssh-action@master
          with:
            host: ${{ secrets.HOSTNAME }}
            username: ${{ secrets.USER_NAME }}
            key: ${{ secrets.AWS_PRIVATE_KEY }}
            script: |
              cd /var/www/html/economyControl
              git checkout master
              git fetch --all
              git reset --hard origin/master
              git pull origin master

