
kind: pipeline
name: remote ssh command
on:
  push:
    branches:
      - main
steps:
  - name: ssh
    image: appleboy/drone-ssh
    settings:
      host:
        from_secret: REMOTE_HOST
      username:
        from_secret: USERNAME
      key:
        from_secret: SSH_PRIVATE_KEY
      target:
        from_secret: TARGET_DIR
      script:
        - echo "hello"
        - echo "deploy"
